[package]
name = "line"
version = "0.1.0"
edition = "2018"

[dependencies]
piston = "0.45.0"
piston2d-opengl_graphics = "0.78.0"
piston2d-graphics = "0.40.0"
pistoncore-glutin_window = "0.69.0"
piston_window = "0.120.0"
find_folder = "0.3.0"